import type { ExportFormState } from "../types/exportacion.types";

export const initialExportFormState: ExportFormState = {
  icoterm: "",
  tipo: "",
  cantidadContenedores: "",
  tamanoTipoContenedor: "",
  cantidadContenedores20: "",
  cantidadContenedores40: "",
  fechaMaterialListo: "",
  consignatario: [],
  ordenCompraSistema: "",
  ordenCompraProveedor: "",
  puertoSalida: "",
  puertoLlegada: "",
  proveedor: "",
  datosFiscalesProveedor: "",
  informacionContactoProveedor: "",
  comentarios: "",
};

export const incotermOptions = [
  "Importacion FOB",
  "Importacion CIF",
  "Importacion EXW",
  "Cotizacion Informativa",
];

export const tipoOptions = [
  "Contenedor",
  "Consolidado",
];

export const cantidadContenedoresOptions = Array.from(
  { length: 20 },
  (_, index) => String(index + 1)
);

export const tamanoContenedorOptions = [
  "20",
  "40",
  "Varios",
];

export const consignatarioOptions = [
  "DIREGO COLOMBIA SAS",
  "DISTRIBUIDORA DE SUSPENSIONES Y FRENOS",
  "DUROTHANE",
  "KATAI INDUSTRIES",
  "KATAI LEAF SPRING COMPANY",
  "MAYORISTA INTERNACIONAL AUTOMOTRIZ",
  "MAYORISTA LATINOAMERICANA",
  "NEGOCIOS Y TRACTOPARTES DE DISTRIBUIDORA DE REFACCIONES DEL GOLFO",
  "TRUCK AND TRAILER COMPONENTS",
];

export const puertoSalidaOptions = [
  "AMBARLI",
  "GUANGZHOU",
  "HAMBURGO",
  "HOCHIMINH",
  "HUANGPU",
  "ISTAMBUL",
  "KAOHSIUNG",
  "NINGBO",
  "QINGDAO",
  "SHANGHAI",
  "SHENZHEN",
  "TIANJIN",
  "WENZHOU",
  "XIAMEN",
  "YANGZHOU",
];

export const puertoLlegadaOptions = [
  "ALTAMIRA",
  "BUENAVENTURA",
  "CARTAGENA",
  "GUAYMAS",
  "MANZANILLO",
  "MAZATLAN",
  "MONTERREY",
];


export const proveedorOptions = [
  "HANGZHOU DAOMING KECHUANG NEW MATERIAL CO LTD",
  "HANGZHOU ZHONGNIU IMPORT & EXPORT CO., LTD",
  "HENAN HAZCHIN AUTO LEAF SPRINGS CO., LTD.",
  "HMS OZCEYLANLAR HIDROLIK MAKINA SAN. TIC. A.S.",
  "HONGKONG TENOW INTERNATIONAL LTD",
  "INTRAC, INC",
  "JIANGSU MIAO RUN SEN LOGISTICS TECHNOLOGY CO. LTD",
  "JIAXING GUANGTAI LIGHTING CO., LTD",
  "JINJIANG ZIHUI MACHINERY FITTINGS CO LTD.",
  "JIULONG INDUSTRIAL CO.,LIMITED",
  "JOST BRASIL SISTEMAS AUTOMOTIVOS LTDA",
  "JOST INTERNATIONAL CO.",
  "MARKET UNION CO., LTD",
  "MARKET UNION CO., LTD, ADD INDUSTRY (ZHEJIANG) CO., LTD",
  "MEKPA OTOMOTIV ITHALAT-IHRACAT SAN.VE TIC. LTD. STI",
  "NINGBO FORTUNE AUTO PARTS MANUFACTURE CO., LTD",
  "NINGBO FORTUNE FYC IMPORT & EXPORT CO",
  "O-TECH (SHANGHAI) INC.",
  "POLYWAY INDUSTRY CO., LTD",
  "R.L. STEELS AND ENERGY LTD",
  "SAF HOLLAND INTERNATIONAL DE MEXICO",
  "SGBO AUTO PARTS INC",
  "SHANDONG CONMET MECHANICAL CO., LTD.",
  "SHANDONG GENERAL TECHNOLOGY CO., LTD",
  "SHANDONG JINLI NEW MATERIAL TECHNOLOGY CO., LTD.",
  "SHANDONG LONGJI MACHINERY CO., LTD",
  "SHENTOU INVESTMENTS (HONGKONG) LIMITED",
  "SPECTRA PREMIUM",
  "STEMCO VEHICLE TEHNOLOGY SUZHOU CO., LT",
  "SUZHOU QUICK LASER TECHNOLOGY CO., LTD",
  "SUZHOU RUNMAX CO., LTD",
  "WEISS ANLAGENTECHNIK GMBH & CO. KG",
  "WENLING DLZ MACHINERY MANUFACTURING CO.,LTD",
  "WENZHOU WANZHENG AUTOMOBILE PUMP CO., LTD",
  "WENZHOU ZHONGYE COMMUNICATION ELECTRIC APPARATUS CO. LTD",
  "WORLDWISE INDUSTRIES LIMITED",
  "XIAMEN TOPU IMPORT & EXPORT CO.,LTD",
  "YANGZHOU TONGHAI AUTO PARTS CO.,LTD",
  "YITAO AIR SPRING GROUP",
  "YUYAO HOJA LIGHTING PRODUCTS CO.,LTD",
  "ZHEJIANG MASTER INJECTION SYSTEM CO., LTD.",
  "ZHEJIANG ODM TRANSMISSION TECHNOLOGY CO.,LTD",
  "ZHEJIANG QUANJIA AUTO PARTS CO,LTD. AND ADD INDUSTRY ( ZHEJIANG) CO.,LTD.",
  "ZHEJIANG SONGDE AUTO PARTS MANUFACTURING CO.,LTD",
  "ZHEJIANG TRK TRADING CO., LTD",
  "ZHEJIANG VIE SCIENCE & TECHNOLOGY CO., LTD.",
  "ZHEJIANG XILI TRADING CO.,LTD",
  "ZHENGZHOU JINGYIDA AUTO PARTS CO., LTD.",
  "ZHONGCE RUBBER GROUP CO., LTD.",
  "ZIBO QIANHENG AUTOMATION ENGINEERING CO., LTD",
];
